spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/helpdesk-application
  # cache connection information
  redis:
    host: localhost
    port: 6379
    timeout: 10000 # in milliseconds

  # caching configuration
  cache:
    redis:
      cache-null-values: false
      # use the following two in conjunction
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000 # in milliseconds
  application:
    name: helpdesk-application

service:
  api:
    version: 0.0.1
  organization:
    name: Tropic World Paradise
