spring:
  profiles:
    active: dev
  activemq:
    broker-url: tcp://localhost:61616
    user:
    password:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/helpdesk-application
  # cache connection information
  redis:
    host:
    port:
    timeout: 10000 # in milliseconds
  # caching configuration
  cache:
    redis:
      cache-null-values: false
      # use the following two in conjunction
      use-key-prefix: true
      key-prefix: poa
      time-to-live: 60000 # in milliseconds
  application:
    name: helpdesk-application

application:
  api:
    version: 0.0.1
  organization:
    name: Poa Internet
  security:
    jwt-secret:
    jwt-expiration-ms:  # expires after 1 hr
    xsrf-secret:

africastalking:
  sms-api-key:
  application-name:

